services:
  web:
    build: ./
    ports:
      - "5001:5001"
    restart: always
  init-db:
    build: ./
    command: python app/scripts/create_db.py --reset
  inset-data:
    build: ./
    command: python app/scripts/insert_posts_data.py